// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpID9L3zkrN86C_Kwr2jD4V3ZHVMbiR8g',
    appId: '1:531888142344:android:bd47bf39d806d0b16ab9bd',
    messagingSenderId: '531888142344',
    projectId: 'uwuemploy',
    storageBucket: 'uwuemploy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv0KyDuOrXk8SMuNo7kK2HkviGivxOqiQ',
    appId: '1:531888142344:ios:81c8e4decfef20d96ab9bd',
    messagingSenderId: '531888142344',
    projectId: 'uwuemploy',
    storageBucket: 'uwuemploy.firebasestorage.app',
    iosBundleId: 'com.example.uempy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv0KyDuOrXk8SMuNo7kK2HkviGivxOqiQ',
    appId: '1:531888142344:ios:81c8e4decfef20d96ab9bd',
    messagingSenderId: '531888142344',
    projectId: 'uwuemploy',
    storageBucket: 'uwuemploy.firebasestorage.app',
    iosBundleId: 'com.example.uempy',
  );
}
